import { z } from 'zod';

/**
 * Schema for context information to help the agent understand the codebase
 */
export const TaskContextSchema = z.object({
  files_to_read: z.array(z.string())
    .optional()
    .describe('Files the agent should read first to understand patterns and context'),

  patterns_to_follow: z.array(z.string())
    .optional()
    .describe('Existing patterns or conventions to match (e.g., "See error handling in docker.ts")'),

  related_code: z.array(z.string())
    .optional()
    .describe('Other files that might be affected by this change'),
});

/**
 * Schema for implementation guidance
 */
export const TaskImplementationSchema = z.object({
  approach: z.string()
    .optional()
    .describe('Suggested implementation approach'),

  files_to_modify: z.array(z.string())
    .optional()
    .describe('Primary files that need changes'),

  files_to_create: z.array(z.string())
    .optional()
    .describe('New files to add'),

  avoid: z.array(z.string())
    .optional()
    .describe('Things NOT to do (constraints)'),
});

/**
 * Schema for verification steps before PR submission
 */
export const TaskVerificationSchema = z.object({
  run_tests: z.boolean()
    .default(true)
    .describe('Whether to run tests before submitting PR'),

  run_lint: z.boolean()
    .default(true)
    .describe('Whether to run linting before submitting PR'),

  run_build: z.boolean()
    .default(true)
    .describe('Whether to run build before submitting PR'),

  custom_checks: z.array(z.string())
    .optional()
    .describe('Additional commands to run (e.g., ["pnpm typecheck", "pnpm test:e2e"])'),
});

/**
 * Schema for a single task generated by the LLM
 *
 * Enhanced with context, acceptance criteria, implementation hints, and verification steps
 * based on async coding agent best practices.
 *
 * @see https://elite-ai-assisted-coding.dev/p/working-with-asynchronous-coding-agents
 */
export const TaskSchema = z.object({
  // === Core fields (existing) ===
  prompt: z.string()
    .min(10, 'Task prompt must be at least 10 characters')
    .max(2000, 'Task prompt must not exceed 2000 characters')
    .describe('Detailed description of the coding task to be performed'),

  priority: z.enum(['high', 'medium', 'low'])
    .describe('Task priority level: high for CI failures, medium for features, low for maintenance'),

  repo: z.string()
    .optional()
    .describe('Target repository (owner/repo format). If omitted, uses default_repo from config.'),

  depends_on: z.array(z.string())
    .default([])
    .describe('Array of task IDs that must complete before this task can start'),

  // === Enhanced fields (new) ===
  context: TaskContextSchema
    .optional()
    .describe('Context to help the agent understand the codebase before starting'),

  acceptance_criteria: z.array(z.string())
    .optional()
    .describe('Specific, testable conditions that define task success'),

  implementation: TaskImplementationSchema
    .optional()
    .describe('Hints about how to implement the task'),

  verification: TaskVerificationSchema
    .optional()
    .describe('Steps to verify the change works before submitting PR'),
});

/**
 * Schema for the array of tasks returned by the LLM
 */
export const TaskArraySchema = z.array(TaskSchema);

/**
 * Type for a single task (inferred from schema)
 */
export type Task = z.infer<typeof TaskSchema>;

/**
 * Type for an array of tasks (inferred from schema)
 */
export type TaskArray = z.infer<typeof TaskArraySchema>;

/**
 * Schema validation error with helpful context
 */
export interface ValidationError {
  message: string;
  path: string[];
  received: unknown;
}

/**
 * Validate LLM response against task schema
 *
 * @param data - Unknown data to validate
 * @returns Validation result with success flag and data/errors
 */
export function validateTaskArray(data: unknown): {
  success: true;
  data: TaskArray;
} | {
  success: false;
  errors: ValidationError[];
} {
  const result = TaskArraySchema.safeParse(data);

  if (result.success) {
    return { success: true, data: result.data };
  }

  // Transform Zod errors into more readable format
  const errors: ValidationError[] = result.error.issues.map((err) => ({
    message: err.message,
    path: err.path.map((p) => String(p)),
    received: err.path.reduce((obj: any, key) => obj?.[key], data),
  }));

  return { success: false, errors };
}

/**
 * Format validation errors into a human-readable string for LLM feedback
 *
 * @param errors - Array of validation errors
 * @returns Formatted error message
 */
export function formatValidationErrors(errors: ValidationError[]): string {
  if (errors.length === 0) return 'Unknown validation error';

  const errorMessages = errors.map(err => {
    const path = err.path.length > 0 ? ` at ${err.path.join('.')}` : '';
    return `- ${err.message}${path}`;
  });

  return `Validation errors:\n${errorMessages.join('\n')}`;
}

/**
 * Example tasks to include in the LLM prompt - showing full specification format
 */
export const TASK_EXAMPLES: Task[] = [
  {
    prompt: 'Fix failing CI build in packages/core: TypeError in container.ts line 145. The startTaskContainer function is missing null check for config.workerImage.',
    priority: 'high',
    repo: 'org/main-repo',
    depends_on: [],
    context: {
      files_to_read: [
        'packages/core/src/worker/container.ts',
        'packages/core/src/worker/types.ts',
      ],
      patterns_to_follow: [
        'See error handling in docker.ts for similar null checks',
      ],
    },
    acceptance_criteria: [
      'CI build passes on main branch',
      'No regression in existing container tests',
      'Missing workerImage throws descriptive ContainerError',
    ],
    implementation: {
      approach: 'Add null/undefined check before accessing config.workerImage, throw ContainerError if missing',
      files_to_modify: ['packages/core/src/worker/container.ts'],
      avoid: ['Do not change the function signature'],
    },
    verification: {
      run_tests: true,
      run_lint: true,
      run_build: true,
      custom_checks: ['pnpm test --filter=@squire/core'],
    },
  },
  {
    prompt: 'Add structured error types for better error handling: ContainerError, GitHubAPIError, and LLMError with error codes and retryable flags.',
    priority: 'medium',
    depends_on: [],
    context: {
      files_to_read: [
        'packages/core/src/utils/logger.ts',
        'packages/core/src/worker/container.ts',
      ],
      patterns_to_follow: [
        'Follow existing logging patterns',
        'Use similar structure to Node.js built-in errors',
      ],
    },
    acceptance_criteria: [
      'New error types exported from @squire/core',
      'Errors include code, message, and isRetryable properties',
      'Existing error handling updated to use new types',
      'Unit tests for each error type',
    ],
    implementation: {
      files_to_create: ['packages/core/src/errors/index.ts'],
      files_to_modify: [
        'packages/core/src/index.ts',
        'packages/core/src/worker/container.ts',
      ],
    },
    verification: {
      run_tests: true,
      run_lint: true,
      run_build: true,
    },
  },
  {
    prompt: 'Update CLAUDE.md documentation to reflect new container timeout and resource limit configuration options.',
    priority: 'low',
    repo: 'org/main-repo',
    depends_on: [],
    acceptance_criteria: [
      'All new config options are documented',
      'Examples show correct usage',
      'No broken markdown links',
    ],
    implementation: {
      files_to_modify: ['CLAUDE.md'],
      approach: 'Add new section under Configuration for container settings',
    },
    verification: {
      run_tests: false,
      run_lint: true,
      run_build: false,
    },
  },
];

/**
 * Generate JSON schema string for inclusion in prompts
 */
export function getSchemaDescription(): string {
  return `{
  "type": "array",
  "items": {
    "type": "object",
    "required": ["prompt", "priority"],
    "properties": {
      "prompt": {
        "type": "string",
        "minLength": 10,
        "maxLength": 2000,
        "description": "Detailed description of the coding task"
      },
      "priority": {
        "type": "string",
        "enum": ["high", "medium", "low"],
        "description": "high=CI failures, medium=features, low=maintenance"
      },
      "repo": {
        "type": "string",
        "description": "Target repo (owner/repo). Optional - uses default if omitted."
      },
      "depends_on": {
        "type": "array",
        "items": { "type": "string" },
        "default": [],
        "description": "Task IDs that must complete first"
      },
      "context": {
        "type": "object",
        "description": "Help the agent understand the codebase",
        "properties": {
          "files_to_read": { "type": "array", "items": { "type": "string" }, "description": "Files to examine first" },
          "patterns_to_follow": { "type": "array", "items": { "type": "string" }, "description": "Conventions to match" },
          "related_code": { "type": "array", "items": { "type": "string" }, "description": "Other affected files" }
        }
      },
      "acceptance_criteria": {
        "type": "array",
        "items": { "type": "string" },
        "description": "Specific, testable conditions for success"
      },
      "implementation": {
        "type": "object",
        "description": "Hints about how to implement",
        "properties": {
          "approach": { "type": "string", "description": "Suggested approach" },
          "files_to_modify": { "type": "array", "items": { "type": "string" } },
          "files_to_create": { "type": "array", "items": { "type": "string" } },
          "avoid": { "type": "array", "items": { "type": "string" }, "description": "Constraints" }
        }
      },
      "verification": {
        "type": "object",
        "description": "Steps before PR submission",
        "properties": {
          "run_tests": { "type": "boolean", "default": true },
          "run_lint": { "type": "boolean", "default": true },
          "run_build": { "type": "boolean", "default": true },
          "custom_checks": { "type": "array", "items": { "type": "string" } }
        }
      }
    }
  }
}`;
}
